"""Agrega columna stock

Revision ID: bb7999dcb518
Revises: 6d0686aa94ec
Create Date: 2026-02-21 03:09:47.282957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7999dcb518'
down_revision: Union[str, Sequence[str], None] = '6d0686aa94ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('stock', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'stock')
    # ### end Alembic commands ###
